FROM python:3.9-alpine

# Copy application code
COPY . /app
WORKDIR /app

# Install dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev
RUN python -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Install azure-ai-translation-text
RUN pip install --no-cache-dir azure-ai-translation-text

# Expose the application port
EXPOSE 5002

# Set environment variables
ENV API_KEY="your-api-key"
ENV ENDPOINT="your-endpoint"
ENV LOCATION="northeurope"

# Start the application
CMD ["python", "app.py"]
